-- Rimuove righe in tgif_knowledge_base inserite con meta-risposte Gemini
-- (disclaimer "come agronomo", "il testo non contiene agronomia", ecc.)
-- Esegui in Supabase SQL Editor DOPO aver fermato l'ingest.
-- Opzionale: SELECT count(*) prima/dopo per verificare.

DELETE FROM public.tgif_knowledge_base
WHERE soluzione ILIKE '%[libro_universitario:%'
  AND (
    soluzione ILIKE '%devo però precisare%'
    OR soluzione ILIKE '%devo pero precisare%'
    OR soluzione ILIKE '%devo innanzitutto precisare%'
    OR soluzione ILIKE '%pertanto, non mi è possibile%'
    OR soluzione ILIKE '%non tratta direttamente%'
    OR soluzione ILIKE '%non rientrano direttamente%'
    OR soluzione ILIKE '%non affronta direttamente%'
    OR soluzione ILIKE '%non contiene alcun riferimento a patogeni%'
    OR soluzione ILIKE '%non contiene alcun riferimento a problematiche%'
    OR soluzione ILIKE '%non contiene alcun riferimento a pratiche%'
    OR soluzione ILIKE '%non contiene alcun riferimento a fitopatologia%'
    OR soluzione ILIKE '%non c''è contenuto agronomico%'
    OR soluzione ILIKE '%non c''e contenuto agronomico%'
    OR soluzione ILIKE '%nessun contenuto agronomico%'
    OR soluzione ILIKE '%nessuna informazione agronomica%'
    OR soluzione ILIKE '%il testo fornito non contiene%'
    OR soluzione ILIKE '%il testo fornito è%'
    OR soluzione ILIKE '%il contenuto fornito è%'
    OR soluzione ILIKE '%il contenuto del testo è%'
    OR soluzione ILIKE '%il testo è di natura puramente%'
    OR soluzione ILIKE '%il testo è un''estrazione%'
    OR soluzione ILIKE '%il testo è una spiegazione%'
    OR soluzione ILIKE '%il testo è un manuale pratico%'
    OR soluzione ILIKE '%non è possibile riassumere%'
    OR soluzione ILIKE '%non e possibile riassumere%'
    OR soluzione ILIKE '%non è possibile estrarre%'
    OR soluzione ILIKE '%interamente incentrato sulla struttura atomica%'
    OR soluzione ILIKE '%Come agronomo italiano, ho analizzato%'
    OR soluzione ILIKE '%In qualità di agronomo%'
    OR soluzione ILIKE '%in qualità di agronomo%'
    OR soluzione ILIKE '%Cari colleghi agricoltori%'
    OR soluzione ILIKE '%Cari colleghi e tecnici%'
    OR soluzione ILIKE '%Certo, ecco una traduzione%'
    OR soluzione ILIKE '%Certo, ecco il riassunto%'
    OR soluzione ILIKE '%Certo, in qualità di agronomo%'
    OR soluzione ILIKE '%Certo, mi metto nei panni%'
    OR soluzione ILIKE '%Analisi dell''Errore nel Log%'
    OR soluzione ILIKE '%REGOLA TASSATIVA%'
    OR soluzione ILIKE '%regole tassative%'
    OR soluzione ILIKE '%In relazione alle sue regole%'
    OR soluzione ILIKE '%in relazione alle tue regole%'
    OR soluzione ILIKE '%come richiesto dalle regole%'
    OR soluzione ILIKE '%analizzato attentamente il testo che mi hai fornito%'
    OR soluzione ILIKE '%ho analizzato attentamente il testo%'
    OR soluzione ILIKE '%ho esaminato attentamente%'
    OR soluzione ILIKE '%se avessi un testo più pertinente%'
    OR soluzione ILIKE '%sarò lieto di fornirti%'
    OR soluzione ILIKE '%SKIP_NO_AGRONOMY%'
  );
